### ISSUE TITLE
Come up with style guidelines

### ISSUE THREAD

**Issue by milandoshi** [covega/448bFinal#2]

**Comment by covega** [comment]
Lots of sketching - sample set of ~10 websites we'd like to transform 

Identify design principles for both the good and the bad
How do we apply them?

**Comment by covega** [comment]
Check out google material design guide?

Ideas:

overuse of color
navbars
headers properly hierarchical
misuse of screen space

**Comment by covega** [comment]
Task before next meeting:
Look at good websites, identify principles
Look at bad websites, identify principles
Look at how to transform from x to y - as general as possible
